# Generated by Django 4.0.5 on 2022-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
